### ISSUE TITLE
Can't compile with Visual Studio 2015

### ISSUE THREAD

**Issue by Lugdunumn** [d07RiV/SNOParser#1]
I got following errors:

snoparser-master\logger.cpp(85): error C2397: conversion from 'unsigned int' to 'SHORT' requires a narrowing conversion

c1xx : fatal error C1083: Cannot open source file: 'imageblp2.cpp': No such file or directory

c:\program files (x86)\microsoft visual studio 14.0\vc\include\algorithm(3056): error C2280: 'MonValue &MonValue::operator =(const MonValue &)': attempting to reference a deleted function

c:\program files (x86)\microsoft visual studio 14.0\vc\include\algorithm(3056): error C2280: 'SearchList::Item &SearchList::Item::operator =(const SearchList::Item &)': attempting to reference a deleted function

**Comment by d07RiV** [comment]
Unsigned int to short shouldn't be an error, has to be something with your compiler settings.

Fixed the others I think.

**Comment by Lugdunumn** [comment]
Now i got:

c:\program files (x86)\windows kits\10\include\10.0.10586.0\shared\ws2def.h(235): error C2011: 'sockaddr': 'struct' type redefinition

c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winsock2.h(136): error C2011: 'fd_set': 'struct' type redefinition

And many struct type redefinition errors in these 2 headers.

snoparser-master\ngdp.cpp(4): fatal error C1083: Cannot open include file: 'checksum.h': No such file or directory

c1xx : fatal error C1083: Cannot open source file: 'http.cpp': No such file or directory

snoparser-master\logger.cpp(85): error C2397: conversion from 'unsigned int' to 'SHORT' requires a narrowing conversion

I just installed VS2015 and I never touch my compiler settings, I don't understand why get this error.

**Comment by d07RiV** [comment]
Added more files that I forgot to add before.

Can you check which cpp file the first two errors come from? I can't recall using winsock in the files that are currently committed (the http.h file that I'm adding now will include it, though).

I fixed the narrowing conversion thing, though I still don't see why it could be an error and not a warning.

Anyhow, what are you trying to do with this? The program doesn't do anything meaningful, unless you put the functions you need in main(), which might be difficult if you don't understand what's going on in there.

**Comment by Lugdunumn** [comment]
It works this time.
Really appreciate your help, I just want to extract some Diablo III resources to build a Mod for another game.

**Comment by d07RiV** [comment]
Oh okay, lmk if you need help with figuring out which functions to use.
